### ISSUE TITLE
vscode extension fails to start when provided binary path

### ISSUE THREAD

**Issue by cameronbrill** [ast-grep/ast-grep-vscode#244] opened 2024-03-20 14:57 UTC
my team develops in a monorepo with a python service in subdirectory `b/`. we install and use ast-grep only for that service, so the `ast-grep` binary lives in b's virtual environment at `b/.venv/bin/ast-grep`. I configured the ast-grep extension as such:
```
{
	"astGrep.serverPath": "b/.venv/bin/ast-grep",
    "astGrep.configPath": "b/sgconfig.yml",
}
```

This _should_ work, as I can run `b/.venv/bin/ast-grep -h` in my terminal and get output. However, when opening the monorepo in vs code, the ast grep vs code extension says `ast-grep cannot be started. Make sure it is installed." Thus, we cannot currently use the ast-grep vs code extension.

**Comment by HerringtonDarkholme** [comment] 2024-03-20 17:08
hi, can you try setting `serverPath` to absolute path?

**Comment by cameronbrill** [comment] 2024-03-20 20:17
so it seems setting `serverPath` to absolute path allows ast-grep to start (i.e. I don't see the message I was seeing before), however we share vs code workspace settings so that's less than ideal for my teams setup. the way we get this to work with other tools is:
- with ruff, we're able to list a relative path (i.e. `./b/.venv/bin/ruff`)
- for some other python settings, we use the [vs code `workspaceFolder` variable](https://code.visualstudio.com/docs/editor/variables-reference#:~:text=%24%7B-,workspaceFolder,-%7D%20%2D%20/home) (i.e. `${workspaceFolder}/b/.venv/bin/whatever`).

Back to the topic of getting the extension to work, even when specifying the absolute path, while the error I mentioned in the issue body goes away, it seems that the extension is still not working. there are errors that show up when I run ast-grep scan on my codebase, but I am seeing no squiggly lines on the relevant files. Is there a way to view debug logs for the extension? I don't see anything ast-grep related under the vs code `output` tab

**Comment by HerringtonDarkholme** [comment] 2024-03-20 20:46
> Back to the topic of getting the extension to work, even when specifying the absolute path, while the error I mentioned in the issue body goes away, it seems that the extension is still not working.

As far as I can tell from the information you provided, I think the issue should probably be the config path. 

```json
    "astGrep.configPath": "b/sgconfig.yml",
```

The server configPath is not supported yet. only `sgconfig.yml` in root folder is supported at the moment.

**Comment by HerringtonDarkholme** [comment] 2024-03-21 04:25
@cameronbrill I cannot reproduce your issue. Can you provide a repro repo and also your environment?

**Comment by HerringtonDarkholme** [comment] 2024-03-21 05:06
I have pushed a fix to solve the binary server issue. Now it always resolves relative to current workspace directory.

The remaining issue is tracked by #228 .

Thanks!

**Closed by HerringtonDarkholme** 2024-03-21 05:06 UTC
